# 使用的语言
language: node_js

# 使用的nodejs版本
node_js:
  - 12

# 仓库的分支
branches:
  only:
    - master

# # 执行isntall前需要执行的命令
# before_install:true

# 执行install
install:
  - npm install

# 执行命令脚本
script:
  - npm run build
